"""Resolve a fixed final epoch count from the two-epoch calibration run."""

import argparse
import csv
import json
import math
import os
from pathlib import Path


def recommend_final_epochs(
    *,
    budget_hours,
    reserve_fraction,
    calibration_wall_seconds,
    late_epoch_seconds,
    calibration_epochs=2,
    max_epochs=100,
):
    """Return a conservative fixed horizon for the scratch final run.

    The representative epoch duration includes at least the late-augmentation
    epoch. ``wall/calibration_epochs`` also accounts for worker startup,
    checkpointing, and other runtime overhead observed during calibration.
    """
    budget_hours = float(budget_hours)
    reserve_fraction = float(reserve_fraction)
    calibration_wall_seconds = float(calibration_wall_seconds)
    late_epoch_seconds = float(late_epoch_seconds)
    calibration_epochs = int(calibration_epochs)
    max_epochs = int(max_epochs)

    if budget_hours <= 0:
        raise ValueError("budget_hours must be positive")
    if not 0 <= reserve_fraction < 1:
        raise ValueError("reserve_fraction must be in [0, 1)")
    if calibration_wall_seconds <= 0 or late_epoch_seconds <= 0:
        raise ValueError("calibration durations must be positive")
    if calibration_epochs <= 0 or max_epochs <= 0:
        raise ValueError("epoch counts must be positive")

    safe_seconds = budget_hours * 3600.0 * (1.0 - reserve_fraction)
    remaining_seconds = safe_seconds - calibration_wall_seconds
    if remaining_seconds <= 0:
        raise ValueError("calibration exhausted the safe training budget")

    representative_epoch_seconds = max(
        late_epoch_seconds,
        calibration_wall_seconds / calibration_epochs,
    )
    fixed_epochs = min(
        max_epochs,
        int(math.floor(remaining_seconds / representative_epoch_seconds)),
    )
    if fixed_epochs < 1:
        raise ValueError("less than one fixed final epoch fits the budget")

    return {
        "budget_hours": budget_hours,
        "reserve_fraction": reserve_fraction,
        "safe_seconds": safe_seconds,
        "calibration_wall_seconds": calibration_wall_seconds,
        "calibration_epochs": calibration_epochs,
        "late_epoch_seconds": late_epoch_seconds,
        "representative_epoch_seconds": representative_epoch_seconds,
        "remaining_final_seconds": remaining_seconds,
        "max_epochs": max_epochs,
        "recommended_final_epochs": fixed_epochs,
    }


def _read_late_epoch_seconds(history_path):
    with Path(history_path).open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if len(rows) < 2:
        raise ValueError(
            "calibration history must contain two completed epochs"
        )
    return float(rows[-1]["train_time_sec"]), len(rows)


def _atomic_write_text(path, content):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Resolve a fixed final epoch horizon from calibration"
    )
    parser.add_argument("--history", type=Path, required=True)
    parser.add_argument("--calibration-wall-seconds", type=float, required=True)
    parser.add_argument("--budget-hours", type=float, default=480.0)
    parser.add_argument("--reserve-fraction", type=float, default=0.05)
    parser.add_argument("--max-epochs", type=int, default=100)
    parser.add_argument("--output-env", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    return parser.parse_args()


def main():
    args = parse_args()
    late_epoch_seconds, calibration_epochs = _read_late_epoch_seconds(
        args.history
    )
    result = recommend_final_epochs(
        budget_hours=args.budget_hours,
        reserve_fraction=args.reserve_fraction,
        calibration_wall_seconds=args.calibration_wall_seconds,
        late_epoch_seconds=late_epoch_seconds,
        calibration_epochs=calibration_epochs,
        max_epochs=args.max_epochs,
    )
    _atomic_write_text(
        args.output_env,
        "# Generated by scripts/recommend_final_epochs.py\n"
        f"export FINAL_NUM_EPOCHS={result['recommended_final_epochs']}\n",
    )
    _atomic_write_text(
        args.output_json,
        json.dumps(result, indent=2, ensure_ascii=False) + "\n",
    )
    print(
        "Recommended fixed final horizon: "
        f"{result['recommended_final_epochs']} epochs "
        f"(representative epoch "
        f"{result['representative_epoch_seconds']:.1f}s)."
    )
    print(f"Source this file before final training: {args.output_env}")


if __name__ == "__main__":
    main()
